### ISSUE TITLE
Редактиране на информацията в секцията за текстови редактори и набиране на инструктори

### ISSUE THREAD

**Issue by dimitardanailov** [rails-girls-sofia/guides#9]
Трябва да се разрешат проблемите посочени от @mitio за следния pull request #8.

**Comment by mitio** [comment]
Няма нужда от отделно issue за оправяне на проблеми по pull request-и. Самите pull request-и са и issues.

**Comment by dimitardanailov** [comment]
Да на ясно съм, просто съм свикнал по такъв начин да работя.

Issue - то ми помага да не забравям :)
